apiVersion: v1
kind: ConfigMap
metadata:
  name: maximum-atom-generator-778kbf2c7d
  namespace: default
  labels:
    test: test
    app: atom-service
  ownerReferences:
    - apiVersion: pdok.nl/v3
      kind: Atom
      name: maximum
      uid: ""
      blockOwnerDeletion: true
      controller: true
immutable: true
data:
  values.yaml: |
    feeds:
      - xmlname:
          space: ""
          local: ""
        stylesheet: https://test.com/stylesheet
        xmlns: http://www.w3.org/2005/Atom
        georss: http://www.georss.org/georss
        inspire_dls: http://inspire.ec.europa.eu/schemas/inspire_dls/1.0
        lang: nl
        id: https://test.com/path/index.xml
        title: service-title
        subtitle: service-subtitle
        link:
          - href: https://test.com/path/index.xml
            data: null
            rel: self
            type: application/atom+xml
            title: service-title
          - href: https://test.com/csw?uuid=00000000-0000-0000-0000-000000000000
            data: null
            rel: describedby
            type: application/xml
          - href: https://test.com/html/00000000-0000-0000-0000-000000000000
            data: null
            rel: related
            type: text/html
            title: NGR pagina voor deze download service
          - href: https://test.com/open/00000000-0000-0000-0000-000000000000.xml
            data: null
            rel: search
            type: application/opensearchdescription+xml
            title: Open Search document voor INSPIRE Download service PDOK
        rights: rights
        author:
          name: owner-author
          email: owner@author.com
        entry:
          - id: https://test.com/path/feed-1.xml
            title: feed-1-title
            summary: feed-1-subtitle
            link:
              - href: https://test.com/csw?uuid=00000000-0000-0000-0000-000000000001
                data: null
                rel: describedby
                type: application/xml
              - href: https://test.com/path/feed-1.xml
                data: null
                rel: alternate
                type: application/atom+xml
                title: feed-1-title
            polygon: 50 5 50 10 100 10 100 5 50 5
            category:
              - term: https://srs-1.test
                label: srs-1
              - term: https://srs-2.test
                label: srs-2
            spatial_dataset_identifier_code: 00000000-0000-0000-0000-000000000002
            spatial_dataset_identifier_namespace: https://test.com
          - id: https://test.com/path/feed-2.xml
            title: feed-2-title
            summary: feed-2-subtitle
            link:
              - href: https://test.com/csw?uuid=00000000-0000-0000-0000-000000000003
                data: null
                rel: describedby
                type: application/xml
              - href: https://test.com/path/feed-2.xml
                data: null
                rel: alternate
                type: application/atom+xml
                title: feed-2-title
            polygon: 50 5 50 10 100 10 100 5 50 5
            category:
              - term: https://srs-3.test
                label: srs-3
            spatial_dataset_identifier_code: 00000000-0000-0000-0000-000000000004
            spatial_dataset_identifier_namespace: https://test-2.com
      - xmlname:
          space: ""
          local: ""
        stylesheet: https://test.com/stylesheet
        xmlns: ""
        lang: nl
        id: https://test.com/path/feed-1.xml
        title: feed-1-title
        subtitle: feed-1-subtitle
        link:
          - href: https://test.com/path/feed-1.xml
            data: null
            rel: self
          - href: https://test.com/path/index.xml
            data: null
            rel: up
            type: application/atom+xml
            title: Top Atom Download Service Feed
          - href: https://test.com/csw?uuid=00000000-0000-0000-0000-000000000001
            data: null
            rel: describedby
            type: application/xml
          - href: https://test.com/html/00000000-0000-0000-0000-000000000001
            data: null
            rel: related
            type: text/html
            title: NGR pagina voor deze dataset
          - href: https://test.com/encodingrule.pdf
            data: null
            rel: encodingRule
            type: application/pdf
            hreflang: en
            title: Encoding Rules
        rights: rights
        author:
          name: feed-1-author
          email: feed-1@author.com
        entry:
          - id: https://test.com/path/entry-1.xml
            title: entry-1-title
            content: entry-1-content
            link:
              - href: https://test.com/path/downloads/index.json
                data: http://localazurite.blob.azurite/container/prefix-1/index.json
                rel: index
                title: entry-1-title-index.json
              - href: https://test.com/path/downloads/file-1.ext
                data: http://localazurite.blob.azurite/container/prefix-1/file-1.ext
                rel: alternate
                title: entry-1-title-file-1.ext
                time: "2006-01-02T15:04:05Z"
                bbox: 1 10 10 100
            rights: rights
            updated: "2006-01-02T15:04:05Z"
            polygon: 50 5 50 10 100 10 100 5 50 5
            category:
              - term: https://srs-1.test
                label: srs-1
          - id: https://test.com/path/entry-2.xml
            title: entry-2-title
            content: entry-2-content
            link:
              - href: https://test.com/path/downloads/file-2.ext
                data: http://localazurite.blob.azurite/container/prefix-2/file-2.ext
                rel: alternate
                title: entry-2-title-file-2.ext
            rights: rights
            updated: "2006-01-02T15:04:05Z"
            polygon: 50 5 50 10 100 10 100 5 50 5
            category:
              - term: https://srs-2.test
                label: srs-2
      - xmlname:
          space: ""
          local: ""
        stylesheet: https://test.com/stylesheet
        xmlns: ""
        lang: nl
        id: https://test.com/path/feed-2.xml
        title: feed-2-title
        subtitle: feed-2-subtitle
        link:
          - href: https://test.com/path/feed-2.xml
            data: null
            rel: self
          - href: https://test.com/path/index.xml
            data: null
            rel: up
            type: application/atom+xml
            title: Top Atom Download Service Feed
          - href: https://test.com/csw?uuid=00000000-0000-0000-0000-000000000003
            data: null
            rel: describedby
            type: application/xml
          - href: https://test.com/html/00000000-0000-0000-0000-000000000003
            data: null
            rel: related
            type: text/html
            title: NGR pagina voor deze dataset
        rights: rights
        author:
          name: feed-2-author
          email: feed-2@author.com
        entry:
          - id: https://test.com/path/entry-3.xml
            title: feed-2-title
            link:
              - href: https://test.com/path/downloads/file-3.ext
                data: http://localazurite.blob.azurite/container/prefix-3/file-3.ext
                rel: section
                title: feed-2-title-file-3.ext
              - href: https://test.com/path/downloads/file-4.ext
                data: http://localazurite.blob.azurite/container/prefix-3/file-4.ext
                rel: section
                title: feed-2-title-file-4.ext
            rights: rights
            updated: "2006-01-02T15:04:05Z"
            polygon: 50 5 50 10 100 10 100 5 50 5
            category:
              - term: https://srs-3.test
                label: srs-3