apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: maximum-atom-downloads-2
  namespace: default
  labels:
    test: test
    app: atom-service
  ownerReferences:
    - apiVersion: pdok.nl/v3
      kind: Atom
      name: maximum
      uid: ""
      blockOwnerDeletion: true
      controller: true
spec:
  replacePathRegex:
    regex: ^/path/downloads/(file-3.ext|file-4.ext)
    replacement: /container/prefix-3/$1
