apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: maximum-atom-headers
  namespace: default
  labels:
    test: test
    pdok.nl/app: atom-service
  ownerReferences:
    - apiVersion: pdok.nl/v3
      kind: Atom
      name: maximum
      uid: ""
      blockOwnerDeletion: true
      controller: true
spec:
  headers:
    customResponseHeaders:
      Access-Control-Allow-Headers: Content-Type
      Access-Control-Allow-Method: GET, OPTIONS, HEAD
      Access-Control-Allow-Origin: "*"
    contentSecurityPolicy: "default-src 'self';"
    frameDeny: true
