apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: maximum-atom-service
  namespace: default
  labels:
    test: test
    pdok.nl/app: atom-service
  ownerReferences:
    - apiVersion: pdok.nl/v3
      kind: Atom
      name: maximum
      uid: ""
      blockOwnerDeletion: true
      controller: true
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      test: test
      pdok.nl/app: atom-service