---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - pdok.nl
  resources:
  - atoms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pdok.nl
  resources:
  - atoms/finalizers
  verbs:
  - update
- apiGroups:
  - pdok.nl
  resources:
  - atoms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - pdok.nl
  resources:
  - ownerinfoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pdok.nl
  resources:
  - ownerinfoes/status
  verbs:
  - get
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - list
  - update
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets/finalizers
  verbs:
  - update
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets/status
  verbs:
  - get
  - update
- apiGroups:
  - traefik.io
  resources:
  - ingressroutes
  - middlewares
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
