---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - pdok.nl
  resources:
  - atoms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pdok.nl
  resources:
  - atoms/finalizers
  verbs:
  - update
- apiGroups:
  - pdok.nl
  resources:
  - atoms/status
  verbs:
  - get
  - patch
  - update
