apiVersion: pdok.nl/v3
kind: Atom
metadata:
  name: basic
  namespace: test
  labels:
    test: test
spec:
  service:
    baseUrl: https://test.com/path/
    title: service-title
    subtitle: service-subtitle
    ownerInfoRef: owner
    rights: rights
    lang: nl
    datasetFeeds:
      - technicalName: feed
        title: feed-title
        subtitle: feed-subtitle
        author:
          email: feed@author.com
          name: feed-author
        entries:
          - technicalName: entry
            updated: 2006-01-02T15:04:05Z
            downloadlinks:
              - data: container/prefix/file.ext
            srs:
              name: srs
              uri: http://srs.test
            polygon:
              bbox:
                maxx: "10"
                maxy: "100"
                minx: "5"
                miny: "50"
