apiVersion: v1
kind: ConfigMap
metadata:
  name: minimal-atom-generator-55ght59fth
  namespace: default
  labels:
    test: test
    app: atom-service
  ownerReferences:
    - apiVersion: pdok.nl/v3
      kind: Atom
      name: minimal
      uid: ""
      blockOwnerDeletion: true
      controller: true
immutable: true
data:
  values.yaml: |
    feeds:
        - xmlname:
            space: ""
            local: ""
          stylesheet: null
          xmlns: http://www.w3.org/2005/Atom
          georss: http://www.georss.org/georss
          inspire_dls: http://inspire.ec.europa.eu/schemas/inspire_dls/1.0
          lang: nl
          id: https://test.com/path/index.xml
          title: service-title
          subtitle: service-subtitle
          link:
            - href: https://test.com/path/index.xml
              data: null
              rel: self
              type: application/atom+xml
              title: service-title
          rights: rights
          author:
            name: owner-author
            email: owner@author.com
          entry:
            - id: https://test.com/path/feed.xml
              title: feed-title
              summary: feed-subtitle
              link:
                - href: https://test.com/path/feed.xml
                  data: null
                  rel: alternate
                  type: application/atom+xml
                  title: feed-title
              polygon: 50 5 50 10 100 10 100 5 50 5
              category:
                - term: https://srs.test
                  label: srs
        - xmlname:
            space: ""
            local: ""
          stylesheet: null
          xmlns: ""
          lang: nl
          id: https://test.com/path/feed.xml
          title: feed-title
          subtitle: feed-subtitle
          link:
            - href: https://test.com/path/feed.xml
              data: null
              rel: self
            - href: https://test.com/path/index.xml
              data: null
              rel: up
              type: application/atom+xml
              title: Top Atom Download Service Feed
          rights: rights
          author:
            name: feed-author
            email: feed@author.com
          entry:
            - id: https://test.com/path/entry.xml
              title: feed-title
              link:
                - href: https://test.com/path/downloads/file.ext
                  data: http://localazurite.blob.azurite/container/prefix/file.ext
                  rel: alternate
                  title: feed-title-file.ext
              rights: rights
              updated: "2006-01-02T15:04:05Z"
              polygon: 50 5 50 10 100 10 100 5 50 5
              category:
                - term: https://srs.test
                  label: srs
